export enum BOOKMARK_ROUTE {
    GET_BOOKMARKED_STATUS = 'GET_BOOKMARKED_STATUS',
    TOGGLE_BOOKMARKED_STATUS = 'TOGGLE_BOOKMARKED_STATUS'
}

export enum ATTENDANCE_ROUTE {
    TOGGLE_ATTENDING_STATUS = 'TOGGLE_ATTENDING_STATUS',
}